### ISSUE TITLE
ARM64 fails tests 5_8.mo

### ISSUE THREAD

**Issue by pmatos** [racket/ChezScheme#29]
https://github.com/racket/ChezScheme/runs/890229053#step:8:201

```
-------- o=3 cp0=t --------
0a1
> 5_8.mo:Bug in mat box-cas! clause 15 at line 59, char 3 of 5_8.ms
```

**Comment by mflatt** [comment]
This was fixed. If I remember correctly, it was a problem where the test didn't handle a spurious CAS failure.
