### ISSUE TITLE
How to build without knowing the architecture?

### ISSUE THREAD

**Issue by L-as** [racket/ChezScheme#32]
I am making a nix expression for this, and from the guide it says that I have to do
```bash
./configure --pb
make tarm64le.bootquick
./configure
...
```
which *does* work, but only for the tarm64le platform. Is there any way to do some generic `make myplatform.bootquick` so that the build steps, and thus the nix expression, can be cross-platform?

**Comment by mflatt** [comment]
There isn't right now, but adding something like that is a good idea.

**Comment by mflatt** [comment]
I've added support for `make auto.bootquick`, which should do the same thing as `auto` replaced with the inferred machine type. Does that work?

**Comment by L-as** [comment]
Thanks, it works!
