### ISSUE TITLE
Upstream Changes

### ISSUE THREAD

**Issue by sirinath** [racket/ChezScheme#34]
Where it make sense, can changes be upstream regularly. Also add enhancements from upstream repo.

**Comment by sorawee** [comment]
To quote from #33:

> There are a number of pending upstreaming PRs for the cicso/ChezScheme repo, and we'd be happy to submit more as the maintainers' time and interest allows. AArch64 support in the Racket branch depends on significant changes like flonum unboxing, garbage collector revisions, and build-system changes, so it's not easy to upstream without/before some existing PRs plus many other potential intermediate PRs.

For the reverse direction, AFAIK, this repo has always been up-to-date with respect to the upstream.

**Comment by sirinath** [comment]
Maybe some of you can ask for commit rights for the upstream.

**Comment by samth** [comment]
We communicate regularly with the Chez developers, but the limiting factor is their bandwidth, time, and interest in the changes made to this branch.
