### ISSUE TITLE
Tags corresponding to Racket releases

### ISSUE THREAD

**Issue by dpk** [racket/ChezScheme#42]
Up until Racket 7.8 last year this repo was regularly tagged giving stable Racket-Chez versions corresponding to stable Racket versions.

Could this practice be restored, so those of us interested in using Racket’s improvements to Chez separately from Racket itself can do so with moderate guarantees of stability?

**Comment by samth** [comment]
@jbclements I think you misunderstood the request and the current situation in this repository. 

This repository is kept up to date using git subtree. So it serves perfectly for the goal of building Chez Scheme with our changes. Furthermore, effectively all of the upstream changes are merged in to this repository and to racket/racket. 

The request here is just to add a v8.4 tag during the release process next time, which should be an easy addition to the process.

**Comment by jbclements** [comment]
Well, color me surprised. I want to make sure I tag the right version though, what triggers the git subtree operation? 

Related: this page

https://www.atlassian.com/git/tutorials/git-subtree

...suggests that git subtree is built-in to most recent versions of git, but I don't see it in my version of git:

```
pajaro2:/tmp clements> git --version   
git version 2.30.1 (Apple Git-130)
pajaro2:/tmp clements> git help subtree
No manual entry for git-subtree
pajaro2:/tmp clements> 
```

**Comment by samth** [comment]
I believe that @mflatt runs it manually to keep the subtree in sync, with the definitive copy being the subdirectory in racket/racket. Maybe there should be a checklist item to ensure that.

**Comment by mflatt** [comment]
I agree that this is a good idea, and I've added tags `racket-v7.9` through `racket-v8.3`.

Just to confirm the repo and distribution situation:

 * The Racket source release includes a `src/ChezScheme` directory with all needed sources (including submodule dependencies) to build Chez Scheme by itself.

 * Chez Scheme can be built through the `racket/src/ChezScheme` directory in the `racket/racket` repo, too. But that one doesn't have a submodule for `boot/pb`, so a `make pb-fetch` is needed at the repo top level.

 * I periodically extract updates from `racket/racket` and apply them here. Even updates from `cisco/ChezScheme` normally go to `racket/racket` first, and then here.

**Comment by amirouche** [comment]
If I understand correctly, the best way to contribute to this repository is with pull-requests to `racket/racket`?

Another useful information will be at glance view of differences with `cisco/ChezScheme`. Maybe it is somewhere, and missed it. I am willing to go through the git history to gather the changes, and put that small description together. Let me know.

**Comment by mflatt** [comment]
There's a list of the main changes at the end of `README.md`. There could be a bigger list, but I don't know whether that would be worth maintaining.

Examples of things not in the current list: makefile and configure-script reorganization, `assert-unreachable` and its interaction with optimization, more cross-library inlining, split cpnanopass into cpnanopass plus cpprim to reduce peak memory when compiling Chez Scheme itself, revised representation of record-type inheritance for constant-time predicates, more general varargs support in the FFI, `thread-join`, vfasl for faster startup. (My best guess is that a complete list of things at that level would be around 3 or 4 times as long.)

**Comment by jbclements** [comment]
Before this one gets away entirely, shall I add a release checklist item for this? I can either remind you to take action, or you can send me a short script or sequence of instructions.

John

**Comment by mflatt** [comment]
We have a checklist item, so adding the tag is now part of our release process.
