### ISSUE TITLE
Building on OpenBSD i386 (ti3ob)

### ISSUE THREAD

**Issue by alexshendi** [racket/ChezScheme#44]
Hi,
on OpenBSD time_t is 64 bits even on 32-bit platforms.
Therefore:
```#define time_t_bits 0x20```
(line 792 in boot/ti3ob/equates.h) must be changed to:
```#define time_t_bits 0x40```

I guess also something in the generating code must be changed.

Best Regards and happy easter!

**Comment by mflatt** [comment]
Thanks for the report! Commit bcbb6aad1c640be1e9006f11c0c234b299f4707b is intended to fix this.

**Comment by mflatt** [comment]
I think this is now fixed, but please re-open if I have it wrong.
