### ISSUE TITLE
zuo build tool build has gcc hardcoded in

### ISSUE THREAD

**Issue by alexshendi** [racket/ChezScheme#45]
I tried to build used clang. I was successful, except for the very first phase -- building zuo. This seems to have gcc hardcoded in. I eventually caved in and created the following script in ~/bin/gcc:
```
#!/bin/sh

exec clang $*
```

**Comment by mflatt** [comment]
Thanks for the report! The `gcc` comes from the `configure` script's default for `HOSTCC`, but this should be improved. It should default to whatever `CC` plus `CFLAGS` is, and `HOSTCC` should also be documented.

**Comment by mflatt** [comment]
Commit ecdcffa592442f4208385a45b034ced0dd22b5e1 is intended to fix this.

**Comment by mflatt** [comment]
I think this is now fixed, but please re-open if I have it wrong.

**Comment by alexshendi** [comment]
Hi,

thanks for closing this and #44. I can confirm that both fixes work.

Am 25. April 2022 20:20:49 MESZ schrieb Matthew Flatt ***@***.***>:
>Closed #45.
>

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
