### ISSUE TITLE
[FFI][ARM64] Calling variadic C function with `string` argument on Mac with M1 chip produces strange results

### ISSUE THREAD

**Issue by lemvik** [racket/ChezScheme#46]
Hi!

Sorry if this is a wrong repo to post this issue (not sure if I should put it into [Racket](https://github.com/racket/racket) repo, there are just so many issues there not really related to Chez port to ARM64).

I'm getting a strange bug when trying to use FFI to call a variadic function on a threaded ChezScheme (Racket flavour) on an M1-chip MacBook. When I declare the `foreign-procedure` to take a `string` as an argument to be passed as part of variadic argument list, the resulting `char *` pointer is pointing to something not really looking like a string.

Same code seems to work fine on Linux x86-64. 

Minimal (admittedly, ugly) example below.

### Environment

1. Machine
```
victor@victor-mac vararg % uname -a
Darwin victor-mac 21.4.0 Darwin Kernel Version 21.4.0: Mon Feb 21 20:35:58 PST 2022; root:xnu-8020.101.4~2/RELEASE_ARM64_T6000 arm64
```
2. C compiler
```
victor@victor-mac vararg % cc --version
Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: arm64-apple-darwin21.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
3. Scheme - built from [099f500](https://github.com/racket/racket/commit/099f500cd1814d6665ad53f7a740ff7cc6ed12c6), threaded.

### Example

C code:
```C
#include <stdarg.h>
#include <string.h>

static char *stored = 0;

char* get_stored() {
  return stored;
}

void set_stored(int type, va_list param) {
  stored = strdup(va_arg(param, char *));
}

int test_vararg(int type, ...) {
  va_list arg;

  va_start(arg, type);

  set_stored(type, arg);

  va_end(arg);
  return 0;
}
```
The above abomination is compiled with `cc -dynamiclib lib.c -o libtest.dylib`

Scheme REPL:
```scheme
> (load-shared-object "./libtest.dylib")
> (define test-vararg (foreign-procedure "test_vararg" (int string) int))
> (define get-result (foreign-procedure "get_stored" () string))
> (test-vararg 1 "test-value")
0
> (get-result)
"\x6;"
```
When same library is dynamically linked into a C `main` that does effectively the same the result is as expected (`"test-value"`).

### Some context (and another example)

The problem has arisen from a real-world code that tries to use `libcurl` to do an HTTP request. The `libcurl`'s `curl_easy_setopt` is actually a variadic function. I was constantly getting `error 3` (URL is malformed) with the following code:

```scheme
#!chezscheme

(load-shared-object "./libcurl.dylib")

(top-level-program (import (chezscheme))
  (define (curl-request url)
    (let ([curl (initialize)])
      (set-string-option curl +curl-url+ url)
      (set-long-option   curl +curl-follow-redirects+ 1)
      (format #t "~&CURL result: ~a~%" (status->string (perform curl)))
      (cleanup curl))
    url)

  (define +curl-url+              10002)
  (define +curl-follow-redirects+ 52)
  (define initialize              (foreign-procedure "curl_easy_init" () uptr))
  (define cleanup                 (foreign-procedure "curl_easy_cleanup" (uptr) void))
  (define set-string-option       (foreign-procedure "curl_easy_setopt" (uptr int string) int))
  (define set-long-option         (foreign-procedure "curl_easy_setopt" (uptr int long) int))
  (define perform                 (foreign-procedure "curl_easy_perform" (uptr) int))
  (define status->string          (foreign-procedure "curl_easy_strerror" (int) string))

  (curl-request "https://example.com")

  (exit))
```
The code above failed with both `libcurl` bundled with MacOS and with one built from source code (latest `master`). After some digging I found out that when `set-string-option` is called, the actual C function that eventually gets the string ([this one](https://github.com/curl/curl/blob/795ed0508497e89ab583925c3ed867f2710679b1/lib/setopt.c#L57)) is called with pointer to some garbage.

**Comment by lemvik** [comment]
Reason why I post this issue here - after reading #42 I believe that this repo is a sort-of-snapshot of the `racket/racket` subfolder that is updated from time to time. 
I get the same results when using code built from this repo at the current master.

**Comment by mflatt** [comment]
The short answer is that you want

```
(define test-vararg (foreign-procedure (__varargs_after 1) "test_vararg" (int string) int))
```

Longer answer: The type of a variadic function in C is not the same as a non-variadic function with the same actual arguments, and the calling convention can different. On Linux, the rules for variadic arguments tend to produce the same calling pattern as non-variadic arguments, but they produce quite different patterns on AArch64 macOS. The `__varargs_after` ABI modifier in the Racket branch of Chez Scheme lets you say where the "..."s go in the C type, and then the foreign function can be called correctly according to that type.

**Comment by lemvik** [comment]
Thank you, @mflatt! Now the `libcurl` thingy works fine.
