### ISSUE TITLE
Thanks for adding tppc32osx! 👍

### ISSUE THREAD

**Issue by cellularmitosis** [racket/ChezScheme#58]
I've been working on a [package manager](https://github.com/cellularmitosis/leopard.sh) for old PowerPC Macs.

I'd like to report that the latest chezscheme works on 10.4 "Tiger" PowerPC and I've [added it as a package](https://github.com/cellularmitosis/leopard.sh/commit/4f089102b93e4a3dd1241c31ca960e6690121400) 😎.

![chez-imacg3](https://user-images.githubusercontent.com/223396/217161154-e47f58b1-ad24-4802-a657-6252b34968cf.png)

Thanks so much for resurrecting `tppc32osx` support in Chez!

Feel free to close this issue upon reading 😁

**Comment by mflatt** [comment]
Thanks! I'm glad it's useful to someone other than me. 😄
