### ISSUE TITLE
Source releases are not buildable

### ISSUE THREAD

**Issue by ncihnegn** [racket/ChezScheme#61]
I want to build using the source archives in https://github.com/racket/ChezScheme/tags but it does not work.
The submodules are missing.
Is it possible to include the submodules in the archives?

**Comment by mflatt** [comment]
There doesn't appear to be a way to include submodules in the archives of https://github.com/racket/ChezScheme/tags, but I've created https://github.com/racket/ChezScheme/releases for with "racket-v8.1" through "racket-v8.9".

**Comment by ncihnegn** [comment]
Awesome!
